import "@/styles/tailwind.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";

import Navbar from "@/components/organs/Navbar";
import { getDictionary, i18n, type Locale } from "@/lib/locale";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// eslint-disable-next-line
export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  const { nav_menu: navMenu } = await getDictionary(lang);
  return (
    <html lang={lang} dir={lang === "fa" ? "rtl" : ""}>
      <body className={inter.className}>
        <Navbar navMenu={navMenu} />
        {children}
      </body>
    </html>
  );
}
